services:
  - type: web
    name: ponto-backend
    runtime: node
    plan: free
    buildCommand: npm install -g pnpm && pnpm install && pnpm build
    startCommand: pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://ponto-frontend.onrender.com # Ajuste para o URL do seu frontend quando estiver disponível
