services:
  - type: web
    name: ritmo-app-api-qa
    env: node
    branch: hml
    buildCommand: npm install && npm run build
    startCommand: npm run start:render
    plan: free
    # Importante: Configuração para garantir que o Render detecte a porta corretamente
    healthCheckPath: /api/docs
    # Configuração para aumentar o tempo de espera antes de considerar o serviço como falho
    healthCheckTimeout: 300
    # Configuração para aumentar o tempo de inicialização permitido e executar verificações de pré-deploy
    initialDeployHook: node render-env-setup.js && node pre-deploy-check.js && sleep 10
    envVars:
      - key: NODE_ENV
        value: qa
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://ritmodb_user:mO3C7prhkLyfshsO6Qt5vz26A9rK7iQp@dpg-d0reskumcj7s7387b6t0-a/ritmodb
      - key: INTERNAL_DATABASE_URL
        value: postgresql://ritmodb_user:mO3C7prhkLyfshsO6Qt5vz26A9rK7iQp@dpg-d0reskumcj7s7387b6t0-a/ritmodb
      - key: DB_SYNCHRONIZE
        value: "true"
      - key: DB_MIGRATIONS_RUN
        value: "true"
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        fromGroup: qa-secrets
      - key: JWT_EXPIRATION
        value: 1d
      - key: CORS_ORIGIN
        value: "*"
