services:
  - type: web
    name: ritmo-app-api-qa
    env: node
    branch: hml
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: qa
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://ritmodb_user:mO3C7prhkLyfshsO6Qt5vz26A9rK7iQp@dpg-d0reskumcj7s7387b6t0-a.oregon-postgres.render.com/ritmodb
      - key: DB_SYNCHRONIZE
        value: true
      - key: DB_MIGRATIONS_RUN
        value: true
      - key: JWT_SECRET
        fromGroup: qa-secrets
      - key: JWT_EXPIRATION
        value: 1d
      - key: CORS_ORIGIN
        value: "*"
